version: 0.2

phases:
  install:
    commands:
      - pip install -r etl/deploy/requirements.txt --upgrade

  pre_build:
    commands:
      - npm -v
      - python --version
      - aws sts get-caller-identity

  build:
    commands:
      - set -xe
      - cd etl
      -
