version: 0.2

phases:
  install:
    commands:
      - pip install -r etl/requirements.txt --upgrade

  pre_build:
    commands:
      - npm -v
      - python --version
      - aws sts get-caller-identity

  build:
    commands:
      - set -xe
      - cd etl/app
      - python setup.py bdist_egg
      - aws s3 cp dist/*.egg s3://sid-emr-spark-application/
      - aws s3 cp __main__.py s3://sid-emr-spark-application/
      - cd ../..
      - aws s3 sync ./dags s3://sid-emr-test-dags
